### ISSUE TITLE
evm/loader: assertion failed: !values.is_empty()

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/plonk-verifier#7]
This happens with the test branch: test branch: https://github.com/privacy-scaling-explorations/zkevm-chain/compare/master...pinkiebell:zkevm-chain-fork:verifier

The `examples/` from plonk-verifier are working but not with the super circuit.

backtrace:
```
thread 'verifier_autogen' panicked at 'assertion failed: !values.is_empty()', /target/cargo/git/checkouts/plonk-verifier-755858dad3193220/9fa07d1/src/loader/evm/loader.rs:939:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/panicking.rs:48:5
   3: plonk_verifier::loader::LoadedScalar::sum_products
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   5: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold
   6: <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter
   7: <plonk_verifier::scheme::kzg::accumulation::plonk::PlonkAccumulationScheme as plonk_verifier::scheme::kzg::accumulation::AccumulationScheme<C,L,T,S>>::accumulate
   8: core::ops::function::FnOnce::call_once
   9: core::ops::function::FnOnce::call_once
             at /rustc/015a824f2dffe32707fceb59c47effaf7b73486c/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test verifier_autogen ... FAILED
```

**Comment by pinkiebell** [comment]
Note: the plonk-verifier fork is based on #5 . This fork includes fixes to make cargo happy. But it also removes
```
-halo2_proofs = { git = "https://github.com/han0110/halo2", branch = "feature/configurable-instance-query", package = "halo2_proofs" }
```
and uses upstream pse instead. Could that be the reason?

**Comment by han0110** [comment]
Thanks for reporting! I think it's a mistake I have made (I assume input of sum should always be some values, but the example you are using has a instance column without value, so it panics), will push a fix soon.

**Comment by han0110** [comment]
Hey @pinkiebell, I have push a commit in the same branch to fix this issue, but it also contains some breaking changes, please update the test you are trying with these major changes:

<details>
<summary>Major changes</summary>
<br>

```diff
# ...
- use plonk_verifier::{
-     loader::evm::{EvmLoader, EvmTranscript},
-     protocol::halo2::{compile, Config},
-     scheme::kzg::{AccumulationScheme, PlonkAccumulationScheme, SameCurveAccumulation},
-     util::TranscriptRead,
- };
+ use plonk_verifier::{
+     loader::evm::{EvmLoader, EvmTranscript},
+     pcs::kzg::{Gwc19, KzgOnSameCurve},
+     system::halo2::{compile, Config},
+     util::transcript::TranscriptRead,
+     verifier::{Plonk, PlonkVerifier},
+ };
# ...
-    let instances = num_instance
-        .into_iter()
-        .map(|len| {
-            iter::repeat_with(|| transcript.read_scalar().unwrap())
-                .take(len)
-                .collect_vec()
-        })
-        .collect_vec();
-
-    let mut strategy = SameCurveAccumulation::<_, _, LIMBS, BITS>::default();
-    PlonkAccumulationScheme::accumulate(
-        &protocol,
-        &loader,
-        instances,
-        &mut transcript,
-        &mut strategy,
-    )
-    .unwrap();
-    strategy.finalize(params.get_g()[0], params.g2(), params.s_g2());
+    let instances = num_instance
+        .into_iter()
+        .map(|len| transcript.read_n_scalars(len).unwrap())
+        .collect::<Vec<_>>();
+    Plonk::<KzgOnSameCurve<Bn256, Gwc19<Bn256>, LIMBS, BITS>>::verify(
+        &params.get_g()[0],
+        &(params.g2(), params.s_g2()),
+        &protocol,
+        &instances,
+        &mut transcript,
+    )
+    .unwrap();
# ...
```
</details>

**Comment by pinkiebell** [comment]
@han0110 Thanks! This works now. The runtime code is  > 1GiB . So this probably depends on #6  ?

I can test with a minimal PublicInput circuit in the meantime, but this will probably be also too big to deploy

**Comment by pinkiebell** [comment]
I wasn't able to test the aggregation with the supercircuit yet because the memory requirements seems to be grown heavily. But that's another problem. This issue is resolved :)
